compliance_gates:
  hipaa:
    access_control_review: true
    audit_logging: true
    encryption_check: true
  sox:
    audit_trail_validation: true
    change_control: true
    segregation_of_duties: true
quality_gates:
  lint:
    required: true
    threshold: 0
  security_scan:
    critical_threshold: 0
    high_threshold: 0
    required: true
  test_coverage:
    required: true
    threshold: 80
