# Intelligent Rule Precedence Configuration
# Defines advanced conflict resolution strategies and industry-specific adjustments

# Base precedence order (from governance-precedence.mdc)
base_precedence:
  - "F8-security-and-compliance-overlay"
  - "8-auditor-validator-protocol"
  - "4-master-rule-code-modification-safety-protocol"
  - "3-master-rule-code-quality-checklist"
  - "6-master-rule-complex-feature-context-preservation"
  - "2-master-rule-ai-collaboration-guidelines"
  - "5-master-rule-documentation-and-context-guidelines"
  - "7-dev-workflow-command-router"
  - "project-rules"

# Rule type precedence (for tie-breaking)
rule_type_precedence:
  security: 1
  compliance: 2
  industry: 3
  quality: 4
  workflow: 5
  project: 6

# Industry-specific priority adjustments
industry_priority_adjustments:
  healthcare:
    security: 20      # Higher security priority for healthcare
    compliance: 15    # Higher compliance priority
    industry: 10      # Industry rules get priority
    quality: 5        # Slight quality priority
    workflow: 0       # No adjustment
    project: -5       # Lower project rule priority
  
  finance:
    security: 25      # Highest security priority for finance
    compliance: 20    # Very high compliance priority
    industry: 15      # High industry priority
    quality: 10       # Higher quality priority
    workflow: 0       # No adjustment
    project: -10      # Lower project rule priority
  
  ecommerce:
    security: 15      # High security priority
    compliance: 10    # High compliance priority
    industry: 5       # Moderate industry priority
    quality: 10       # Higher quality priority
    workflow: 5       # Slight workflow priority
    project: 0        # No adjustment
  
  enterprise:
    security: 20      # High security priority
    compliance: 15    # High compliance priority
    industry: 10      # High industry priority
    quality: 5        # Slight quality priority
    workflow: 10      # High workflow priority
    project: 0        # No adjustment

# Conflict resolution strategies
conflict_resolution:
  mutually_exclusive:
    strategy: "precedence_based"
    fallback: "human_clarification"
    timeout: 300  # seconds
  
  mergeable:
    strategy: "intelligent_merge"
    merge_parameters: true
    preserve_original_intent: true
  
  composable:
    strategy: "sequential_execution"
    order_by: "priority"
    parallel_allowed: false
  
  requires_clarification:
    strategy: "escalate_to_human"
    auto_retry: false
    escalation_timeout: 600  # seconds

# Intelligent merging rules
merging_rules:
  parameter_merge_strategies:
    lists: "union"           # Combine lists, remove duplicates
    dictionaries: "deep_merge"  # Deep merge dictionaries
    strings: "concatenate"   # Concatenate strings
    numbers: "max"           # Use maximum value
    booleans: "or"           # Use OR logic
  
  action_merge_strategies:
    same_type: "merge_parameters"
    different_type: "compose_sequential"
    conflicting_type: "precedence_resolution"

# Context-aware adjustments
context_adjustments:
  project_size:
    small: 0      # No adjustment
    medium: 5     # Slight priority increase
    large: 10     # Higher priority increase
    enterprise: 15 # Highest priority increase
  
  compliance_requirements:
    none: 0
    basic: 5
    strict: 15
    critical: 25
  
  security_level:
    low: 0
    medium: 10
    high: 20
    maximum: 30

# Audit and monitoring
audit_config:
  log_all_resolutions: true
  log_conflict_details: true
  log_industry_adjustments: true
  log_merge_operations: true
  retention_days: 90
  
  metrics:
    track_resolution_time: true
    track_conflict_frequency: true
    track_industry_accuracy: true
    track_human_escalation_rate: true

# Performance optimization
performance:
  cache_resolutions: true
  cache_ttl: 3600  # seconds
  parallel_conflict_analysis: true
  max_concurrent_analysis: 4
  
  optimization:
    skip_obvious_conflicts: true
    precompute_industry_adjustments: true
    use_rule_dependency_graph: true

# Integration settings
integration:
  with_context_discovery: true
  with_industry_recognition: true
  with_audit_system: true
  with_monitoring: true
  
  api_endpoints:
    resolve_conflicts: "/api/v1/resolve-conflicts"
    get_precedence: "/api/v1/precedence"
    audit_logs: "/api/v1/audit-logs"

# Fallback and error handling
fallback_config:
  on_resolution_failure: "escalate_to_human"
  on_config_error: "use_base_precedence"
  on_timeout: "use_cached_resolution"
  
  error_handling:
    log_errors: true
    notify_on_critical: true
    retry_attempts: 3
    retry_delay: 5  # seconds

# Testing and validation
testing:
  enable_mock_resolutions: false
  validate_resolution_quality: true
  run_conflict_simulation: false
  
  quality_checks:
    check_rule_coverage: true
    validate_industry_adjustments: true
    verify_audit_trail: true
    test_performance: true
