default: true

# Allow long lines; many tables/URLs exceed 80 chars
MD013: false

# Allow <br> and <img> if used in docs
MD033:
  allowed_elements:
    - br
    - img

# Keep newline at end of file and other hygiene checks
MD047: true
