version: '3.8'

services:
  dev:
    build: .
    volumes:
      - .:/workspace
    ports:
      - 3000:3000
      - 8000:8000
    environment:
      - NODE_ENV=development
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
