version: '3.8'

services:
  dev:
    build: .
    volumes:
      - .:/workspace
    ports:
      - 3000:3000
      - 8000:8000
    environment:
      - NODE_ENV=development
  mongodb:
    image: mongo:6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
