# Context Cache Configuration
# Defines caching strategies and performance optimization settings

# Cache storage settings
storage:
  cache_directory: ".cursor/dev-workflow/cache"
  max_size_mb: 100
  compression: true
  serialization_format: "pickle"  # pickle, json, msgpack
  
  persistence:
    auto_save: true
    save_interval: 300  # seconds
    backup_on_shutdown: true
    max_backups: 5

# TTL (Time To Live) settings
ttl:
  default: 3600  # 1 hour
  minimum: 300   # 5 minutes
  maximum: 86400 # 24 hours
  
  # Industry-specific TTL adjustments
  industry_adjustments:
    healthcare: 3600    # 1 hour - high compliance requirements
    finance: 7200       # 2 hours - high security requirements
    ecommerce: 3600     # 1 hour - moderate requirements
    enterprise: 5400    # 1.5 hours - moderate requirements
    consumer_mobile: 3600 # 1 hour - moderate requirements
    default: 3600       # 1 hour default
  
  # Rule type-specific TTL adjustments
  rule_type_adjustments:
    security: 1800      # 30 minutes - frequently changing
    compliance: 3600    # 1 hour - moderately stable
    industry: 7200      # 2 hours - stable
    quality: 5400       # 1.5 hours - moderately stable
    workflow: 3600      # 1 hour - moderately stable
    project: 7200       # 2 hours - stable
  
  # Operation-specific TTL adjustments
  operation_adjustments:
    context_discovery: 3600     # 1 hour
    industry_classification: 7200 # 2 hours
    rule_activation: 1800       # 30 minutes
    compliance_mapping: 3600    # 1 hour
    tech_stack_analysis: 5400   # 1.5 hours

# Cache invalidation settings
invalidation:
  # File system monitoring
  file_system_monitoring: true
  watch_patterns:
    - "**/*.mdc"        # Rule files
    - "**/*.md"         # Documentation files
    - "**/package.json" # Package files
    - "**/requirements.txt" # Python requirements
    - "**/README.md"    # README files
  
  # Dependency-based invalidation
  dependency_tracking: true
  dependency_types:
    - "rule_dependencies"
    - "file_dependencies"
    - "industry_dependencies"
    - "compliance_dependencies"
  
  # Time-based invalidation
  time_based:
    max_age: 86400      # 24 hours maximum age
    cleanup_interval: 3600 # 1 hour cleanup interval
    force_refresh_interval: 21600 # 6 hours force refresh

# Performance optimization
performance:
  # Memory management
  memory_management:
    max_entries: 1000
    eviction_policy: "lru"  # lru, lfu, ttl
    memory_threshold: 0.8   # 80% memory usage threshold
  
  # Access pattern optimization
  access_optimization:
    track_access_patterns: true
    optimize_ttl_based_on_usage: true
    high_frequency_threshold: 10
    low_frequency_threshold: 2
    ttl_multiplier: 1.5
    ttl_divisor: 2
  
  # Background processing
  background_processing:
    cleanup_thread: true
    optimization_thread: true
    stats_collection: true
    cleanup_interval: 60    # seconds
    optimization_interval: 300 # seconds

# Cache statistics and monitoring
monitoring:
  # Statistics collection
  stats_collection:
    enabled: true
    track_hit_rate: true
    track_access_patterns: true
    track_eviction_patterns: true
    track_size_growth: true
  
  # Performance metrics
  metrics:
    hit_rate_threshold: 0.8    # 80% hit rate target
    average_access_time_threshold: 0.1 # 100ms target
    size_growth_threshold: 0.1  # 10% growth per hour
    eviction_rate_threshold: 0.1 # 10% eviction rate
  
  # Alerting
  alerting:
    enabled: true
    low_hit_rate_alert: true
    high_eviction_rate_alert: true
    size_limit_alert: true
    performance_degradation_alert: true

# Cache warming strategies
warming:
  # Preload frequently used contexts
  preload_frequent_contexts: true
  preload_industry_contexts: true
  preload_rule_contexts: true
  
  # Predictive loading
  predictive_loading: true
  prediction_models:
    - "industry_pattern_matching"
    - "project_structure_analysis"
    - "user_behavior_patterns"
  
  # Warmup strategies
  strategies:
    - "cold_start_optimization"
    - "industry_specific_warming"
    - "rule_dependency_warming"

# Security and privacy
security:
  # Data encryption
  encryption:
    enabled: true  # Enabled by default for healthcare contexts
    algorithm: "AES-256"
    key_rotation_interval: 86400 # 24 hours
  
  # Access control
  access_control:
    enabled: false
    require_authentication: false
    role_based_access: false
  
  # Data sanitization
  sanitization:
    remove_sensitive_data: true
    sanitization_patterns:
      - "password"
      - "secret"
      - "key"
      - "token"
      - "credential"

# Integration settings
integration:
  # Context discovery integration
  context_discovery:
    auto_cache_results: true
    cache_industry_classification: true
    cache_rule_activation: true
    cache_compliance_mapping: true
  
  # Industry recognition integration
  industry_recognition:
    cache_industry_patterns: true
    cache_tech_stack_analysis: true
    cache_compliance_requirements: true
  
  # Rule precedence integration
  rule_precedence:
    cache_conflict_resolutions: true
    cache_precedence_decisions: true
    cache_merge_operations: true

# Debugging and logging
debugging:
  # Logging levels
  logging:
    level: "INFO"  # DEBUG, INFO, WARNING, ERROR
    log_cache_operations: true
    log_performance_metrics: true
    log_invalidation_events: true
  
  # Debug tools
  debug_tools:
    cache_inspector: true
    performance_profiler: true
    dependency_analyzer: true
    invalidation_tracer: true
  
  # Development mode
  development_mode:
    enabled: false
    verbose_logging: false
    cache_validation: true
    performance_profiling: true

# Backup and recovery
backup:
  # Backup settings
  backup:
    enabled: true
    backup_interval: 3600  # 1 hour
    max_backups: 10
    backup_compression: true
  
  # Recovery settings
  recovery:
    auto_recovery: true
    recovery_timeout: 300  # 5 minutes
    fallback_to_defaults: true
  
  # Disaster recovery
  disaster_recovery:
    cross_system_backup: false
    cloud_backup: false
    backup_encryption: false
